#ifndef EZ80_DST_SRC_H
#define EZ80_DST_SRC_H

#include "ez80_instruction.h"
#include "ez80_instruction_info.h"

enum class ez80_arg {
	NONE,
	A,
	B,
	C,
	D,
	E,
	H,
	L,
	IXL,
	IXH,
	IYL,
	IYH,
	UBC,
	UDE,
	UHL,
	UIX,
	UIY,
	BC,
	DE,
	HL,
	IX,
	IY,
	SP,
	AF,
	PHL,
	PDE,
	PBC,
	PIY,
	PIX,
	I,
	MB,
	R,
	PC,
	IMM,
	ADDR,
	PUSH,
	POP,
	MANY,
};


struct ez80_dst_src {
	ez80_op_code op_code;
	ez80_arg dst;
	ez80_arg src;
};

const ez80_dst_src ez80_dst_src_table[] = {
	{ez80_op_code::UNKNOWN       , ez80_arg::NONE , ez80_arg::NONE },

	/* Unary */

	{ez80_op_code::NOP           , ez80_arg::NONE , ez80_arg::NONE },

	{ez80_op_code::SCF           , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::CCF           , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::RLA           , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RLCA          , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RRA           , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RRCA          , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::CPL           , ez80_arg::A    , ez80_arg::A    },

	{ez80_op_code::NEG           , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::DAA           , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RLD           , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::RRD           , ez80_arg::MANY , ez80_arg::MANY },

	{ez80_op_code::EX_AF_AF      , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::EX_DE_HL      , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::EX_DE_HL_SIS  , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::EXX           , ez80_arg::MANY , ez80_arg::MANY },

	/* Processor Control */

	{ez80_op_code::RSMIX         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::SLP           , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::STMIX         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::DI            , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::EI            , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::HALT          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IM_0          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IM_1          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IM_2          , ez80_arg::NONE , ez80_arg::NONE },

	/* Special Registers */

	{ez80_op_code::LD_HL_I       , ez80_arg::HL   , ez80_arg::I    },
	{ez80_op_code::LD_A_I        , ez80_arg::A    , ez80_arg::I    },
	{ez80_op_code::LD_A_R        , ez80_arg::A    , ez80_arg::R    },
	{ez80_op_code::LD_A_MB       , ez80_arg::A    , ez80_arg::MB   },

	{ez80_op_code::LD_MB_A       , ez80_arg::MB   , ez80_arg::A    },
	{ez80_op_code::LD_R_A        , ez80_arg::R    , ez80_arg::A    },
	{ez80_op_code::LD_I_A        , ez80_arg::I    , ez80_arg::A    },
	{ez80_op_code::LD_I_HL       , ez80_arg::I    , ez80_arg::HL   },

	/* Jump Register */

	{ez80_op_code::JP_HL         , ez80_arg::PC   , ez80_arg::PHL  },
	{ez80_op_code::JP_IX         , ez80_arg::PC   , ez80_arg::PIX  },
	{ez80_op_code::JP_IY         , ez80_arg::PC   , ez80_arg::PIY  },

	/* Jump Absolute */

	{ez80_op_code::JP            , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JP_C          , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JP_NC         , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JP_Z          , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JP_NZ         , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JP_P          , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JP_M          , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JP_PO         , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JP_PE         , ez80_arg::PC   , ez80_arg::IMM  },

	/* Jump Relative */

	{ez80_op_code::JR            , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JR_C          , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JR_NC         , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JR_Z          , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::JR_NZ         , ez80_arg::PC   , ez80_arg::IMM  },
	{ez80_op_code::DJNZ          , ez80_arg::MANY , ez80_arg::IMM  },

	/* Call */

	{ez80_op_code::CALL          , ez80_arg::MANY , ez80_arg::IMM  },
	{ez80_op_code::CALL_C        , ez80_arg::MANY , ez80_arg::IMM  },
	{ez80_op_code::CALL_NC       , ez80_arg::MANY , ez80_arg::IMM  },
	{ez80_op_code::CALL_Z        , ez80_arg::MANY , ez80_arg::IMM  },
	{ez80_op_code::CALL_NZ       , ez80_arg::MANY , ez80_arg::IMM  },
	{ez80_op_code::CALL_P        , ez80_arg::MANY , ez80_arg::IMM  },
	{ez80_op_code::CALL_M        , ez80_arg::MANY , ez80_arg::IMM  },
	{ez80_op_code::CALL_PO       , ez80_arg::MANY , ez80_arg::IMM  },
	{ez80_op_code::CALL_PE       , ez80_arg::MANY , ez80_arg::IMM  },

	{ez80_op_code::RST_0         , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RST_8         , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RST_16        , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RST_24        , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RST_32        , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RST_40        , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RST_48        , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RST_56        , ez80_arg::MANY , ez80_arg::NONE },

	/* Return */

	{ez80_op_code::RET           , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RET_C         , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RET_NC        , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RET_Z         , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RET_NZ        , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RET_P         , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RET_M         , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RET_PO        , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RET_PE        , ez80_arg::MANY , ez80_arg::NONE },

	{ez80_op_code::RETI          , ez80_arg::MANY , ez80_arg::NONE },
	{ez80_op_code::RETN          , ez80_arg::MANY , ez80_arg::NONE },

	/* Stack operations */

	{ez80_op_code::PEA_IX        , ez80_arg::PUSH , ez80_arg::IX   },
	{ez80_op_code::PEA_IY        , ez80_arg::PUSH , ez80_arg::IY   },

	{ez80_op_code::POP_AF        , ez80_arg::AF   , ez80_arg::POP  },
	{ez80_op_code::POP_BC        , ez80_arg::BC   , ez80_arg::POP  },
	{ez80_op_code::POP_DE        , ez80_arg::DE   , ez80_arg::POP  },
	{ez80_op_code::POP_HL        , ez80_arg::HL   , ez80_arg::POP  },
	{ez80_op_code::POP_IX        , ez80_arg::IX   , ez80_arg::POP  },
	{ez80_op_code::POP_IY        , ez80_arg::IY   , ez80_arg::POP  },

	{ez80_op_code::PUSH_AF       , ez80_arg::PUSH , ez80_arg::AF   },
	{ez80_op_code::PUSH_BC       , ez80_arg::PUSH , ez80_arg::BC   },
	{ez80_op_code::PUSH_DE       , ez80_arg::PUSH , ez80_arg::DE   },
	{ez80_op_code::PUSH_HL       , ez80_arg::PUSH , ez80_arg::HL   },
	{ez80_op_code::PUSH_IX       , ez80_arg::PUSH , ez80_arg::IX   },
	{ez80_op_code::PUSH_IY       , ez80_arg::PUSH , ez80_arg::IY   },

	{ez80_op_code::EX_SP_HL      , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::EX_SP_IX      , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::EX_SP_IY      , ez80_arg::MANY , ez80_arg::MANY },

	/* Block Transfer and Compare */

	{ez80_op_code::CPD           , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::CPDR          , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::CPI           , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::CPIR          , ez80_arg::MANY , ez80_arg::MANY },

	{ez80_op_code::LDD           , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::LDDR          , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::LDI           , ez80_arg::MANY , ez80_arg::MANY },
	{ez80_op_code::LDIR          , ez80_arg::MANY , ez80_arg::MANY },

	/* Increment */

	{ez80_op_code::INC_A         , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::INC_B         , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::INC_C         , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::INC_D         , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::INC_E         , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::INC_H         , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::INC_L         , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::INC_IXH       , ez80_arg::IXH  , ez80_arg::IXH  },
	{ez80_op_code::INC_IXL       , ez80_arg::IXL  , ez80_arg::IXL  },
	{ez80_op_code::INC_IYH       , ez80_arg::IYH  , ez80_arg::IYH  },
	{ez80_op_code::INC_IYL       , ez80_arg::IYL  , ez80_arg::IYL  },
	{ez80_op_code::INC_PHL       , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::INC_PIX       , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::INC_PIY       , ez80_arg::PIY  , ez80_arg::PIY  },

	{ez80_op_code::INC_BC        , ez80_arg::BC   , ez80_arg::BC   },
	{ez80_op_code::INC_DE        , ez80_arg::DE   , ez80_arg::DE   },
	{ez80_op_code::INC_HL        , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::INC_SP        , ez80_arg::SP   , ez80_arg::SP   },
	{ez80_op_code::INC_IX        , ez80_arg::IX   , ez80_arg::IX   },
	{ez80_op_code::INC_IY        , ez80_arg::IY   , ez80_arg::IY   },

	{ez80_op_code::INC_BC_SIS    , ez80_arg::BC   , ez80_arg::BC   },
	{ez80_op_code::INC_DE_SIS    , ez80_arg::DE   , ez80_arg::DE   },
	{ez80_op_code::INC_HL_SIS    , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::INC_SP_SIS    , ez80_arg::SP   , ez80_arg::SP   },
	{ez80_op_code::INC_IX_SIS    , ez80_arg::IX   , ez80_arg::IX   },
	{ez80_op_code::INC_IY_SIS    , ez80_arg::IY   , ez80_arg::IY   },

	/* Decrement */

	{ez80_op_code::DEC_A         , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::DEC_B         , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::DEC_C         , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::DEC_D         , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::DEC_E         , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::DEC_H         , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::DEC_L         , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::DEC_IXH       , ez80_arg::IXH  , ez80_arg::IXH  },
	{ez80_op_code::DEC_IXL       , ez80_arg::IXL  , ez80_arg::IXL  },
	{ez80_op_code::DEC_IYH       , ez80_arg::IYH  , ez80_arg::IYH  },
	{ez80_op_code::DEC_IYL       , ez80_arg::IYL  , ez80_arg::IYL  },
	{ez80_op_code::DEC_PHL       , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::DEC_PIX       , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::DEC_PIY       , ez80_arg::PIY  , ez80_arg::PIY  },

	{ez80_op_code::DEC_BC        , ez80_arg::BC   , ez80_arg::BC   },
	{ez80_op_code::DEC_DE        , ez80_arg::DE   , ez80_arg::DE   },
	{ez80_op_code::DEC_HL        , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::DEC_SP        , ez80_arg::SP   , ez80_arg::SP   },
	{ez80_op_code::DEC_IX        , ez80_arg::IX   , ez80_arg::IX   },
	{ez80_op_code::DEC_IY        , ez80_arg::IY   , ez80_arg::IY   },

	{ez80_op_code::DEC_BC_SIS    , ez80_arg::BC   , ez80_arg::BC   },
	{ez80_op_code::DEC_DE_SIS    , ez80_arg::DE   , ez80_arg::DE   },
	{ez80_op_code::DEC_HL_SIS    , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::DEC_SP_SIS    , ez80_arg::SP   , ez80_arg::SP   },
	{ez80_op_code::DEC_IX_SIS    , ez80_arg::IX   , ez80_arg::IX   },
	{ez80_op_code::DEC_IY_SIS    , ez80_arg::IY   , ez80_arg::IY   },

	/* Aritmetic Reg24 */

	{ez80_op_code::ADD_HL_BC     , ez80_arg::HL   , ez80_arg::BC   },
	{ez80_op_code::ADD_HL_DE     , ez80_arg::HL   , ez80_arg::DE   },
	{ez80_op_code::ADD_HL_HL     , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::ADD_HL_SP     , ez80_arg::HL   , ez80_arg::SP   },

	{ez80_op_code::ADD_HL_BC_SIS , ez80_arg::HL   , ez80_arg::BC   },
	{ez80_op_code::ADD_HL_DE_SIS , ez80_arg::HL   , ez80_arg::DE   },
	{ez80_op_code::ADD_HL_HL_SIS , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::ADD_HL_SP_SIS , ez80_arg::HL   , ez80_arg::SP   },

	{ez80_op_code::ADD_IX_BC     , ez80_arg::IX   , ez80_arg::BC   },
	{ez80_op_code::ADD_IX_DE     , ez80_arg::IX   , ez80_arg::DE   },
	{ez80_op_code::ADD_IX_IX     , ez80_arg::IX   , ez80_arg::IX   },
	{ez80_op_code::ADD_IX_SP     , ez80_arg::IX   , ez80_arg::SP   },
	{ez80_op_code::ADD_IY_BC     , ez80_arg::IY   , ez80_arg::BC   },
	{ez80_op_code::ADD_IY_DE     , ez80_arg::IY   , ez80_arg::DE   },
	{ez80_op_code::ADD_IY_IY     , ez80_arg::IY   , ez80_arg::IY   },
	{ez80_op_code::ADD_IY_SP     , ez80_arg::IY   , ez80_arg::SP   },

	{ez80_op_code::ADD_IX_BC_SIS , ez80_arg::IX   , ez80_arg::BC   },
	{ez80_op_code::ADD_IX_DE_SIS , ez80_arg::IX   , ez80_arg::DE   },
	{ez80_op_code::ADD_IX_IX_SIS , ez80_arg::IX   , ez80_arg::IX   },
	{ez80_op_code::ADD_IX_SP_SIS , ez80_arg::IX   , ez80_arg::SP   },
	{ez80_op_code::ADD_IY_BC_SIS , ez80_arg::IY   , ez80_arg::BC   },
	{ez80_op_code::ADD_IY_DE_SIS , ez80_arg::IY   , ez80_arg::DE   },
	{ez80_op_code::ADD_IY_IY_SIS , ez80_arg::IY   , ez80_arg::IY   },
	{ez80_op_code::ADD_IY_SP_SIS , ez80_arg::IY   , ez80_arg::SP   },

	{ez80_op_code::ADC_HL_BC     , ez80_arg::HL   , ez80_arg::BC   },
	{ez80_op_code::ADC_HL_DE     , ez80_arg::HL   , ez80_arg::DE   },
	{ez80_op_code::ADC_HL_HL     , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::ADC_HL_SP     , ez80_arg::HL   , ez80_arg::SP   },

	{ez80_op_code::ADC_HL_BC_SIS , ez80_arg::HL   , ez80_arg::BC   },
	{ez80_op_code::ADC_HL_DE_SIS , ez80_arg::HL   , ez80_arg::DE   },
	{ez80_op_code::ADC_HL_HL_SIS , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::ADC_HL_SP_SIS , ez80_arg::HL   , ez80_arg::SP   },

	{ez80_op_code::SBC_HL_BC     , ez80_arg::HL   , ez80_arg::BC   },
	{ez80_op_code::SBC_HL_DE     , ez80_arg::HL   , ez80_arg::DE   },
	{ez80_op_code::SBC_HL_HL     , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::SBC_HL_SP     , ez80_arg::HL   , ez80_arg::SP   },

	{ez80_op_code::SBC_HL_BC_SIS , ez80_arg::HL   , ez80_arg::BC   },
	{ez80_op_code::SBC_HL_DE_SIS , ez80_arg::HL   , ez80_arg::DE   },
	{ez80_op_code::SBC_HL_HL_SIS , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::SBC_HL_SP_SIS , ez80_arg::HL   , ez80_arg::SP   },

	{ez80_op_code::MLT_BC        , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::MLT_DE        , ez80_arg::DE   , ez80_arg::DE   },
	{ez80_op_code::MLT_HL        , ez80_arg::HL   , ez80_arg::HL   },
	{ez80_op_code::MLT_SP        , ez80_arg::SP   , ez80_arg::SP   },

	/* Accumulate Arithmetic */

	{ez80_op_code::ADD_A_N       , ez80_arg::A    , ez80_arg::IMM  },
	{ez80_op_code::ADD_A_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::ADD_A_B       , ez80_arg::A    , ez80_arg::B    },
	{ez80_op_code::ADD_A_C       , ez80_arg::A    , ez80_arg::C    },
	{ez80_op_code::ADD_A_D       , ez80_arg::A    , ez80_arg::D    },
	{ez80_op_code::ADD_A_E       , ez80_arg::A    , ez80_arg::E    },
	{ez80_op_code::ADD_A_H       , ez80_arg::A    , ez80_arg::H    },
	{ez80_op_code::ADD_A_L       , ez80_arg::A    , ez80_arg::L    },
	{ez80_op_code::ADD_A_IXH     , ez80_arg::A    , ez80_arg::IXH  },
	{ez80_op_code::ADD_A_IXL     , ez80_arg::A    , ez80_arg::IXL  },
	{ez80_op_code::ADD_A_IYH     , ez80_arg::A    , ez80_arg::IYH  },
	{ez80_op_code::ADD_A_IYL     , ez80_arg::A    , ez80_arg::IYL  },
	{ez80_op_code::ADD_A_PHL     , ez80_arg::A    , ez80_arg::PHL  },
	{ez80_op_code::ADD_A_PIX     , ez80_arg::A    , ez80_arg::PIX  },
	{ez80_op_code::ADD_A_PIY     , ez80_arg::A    , ez80_arg::PIY  },

	{ez80_op_code::ADC_A_N       , ez80_arg::A    , ez80_arg::IMM  },
	{ez80_op_code::ADC_A_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::ADC_A_B       , ez80_arg::A    , ez80_arg::B    },
	{ez80_op_code::ADC_A_C       , ez80_arg::A    , ez80_arg::C    },
	{ez80_op_code::ADC_A_D       , ez80_arg::A    , ez80_arg::D    },
	{ez80_op_code::ADC_A_E       , ez80_arg::A    , ez80_arg::E    },
	{ez80_op_code::ADC_A_H       , ez80_arg::A    , ez80_arg::H    },
	{ez80_op_code::ADC_A_L       , ez80_arg::A    , ez80_arg::L    },
	{ez80_op_code::ADC_A_IXH     , ez80_arg::A    , ez80_arg::IXH  },
	{ez80_op_code::ADC_A_IXL     , ez80_arg::A    , ez80_arg::IXL  },
	{ez80_op_code::ADC_A_IYH     , ez80_arg::A    , ez80_arg::IYH  },
	{ez80_op_code::ADC_A_IYL     , ez80_arg::A    , ez80_arg::IYL  },
	{ez80_op_code::ADC_A_PHL     , ez80_arg::A    , ez80_arg::PHL  },
	{ez80_op_code::ADC_A_PIX     , ez80_arg::A    , ez80_arg::PIX  },
	{ez80_op_code::ADC_A_PIY     , ez80_arg::A    , ez80_arg::PIY  },

	{ez80_op_code::SUB_A_N       , ez80_arg::A    , ez80_arg::IMM  },
	{ez80_op_code::SUB_A_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SUB_A_B       , ez80_arg::A    , ez80_arg::B    },
	{ez80_op_code::SUB_A_C       , ez80_arg::A    , ez80_arg::C    },
	{ez80_op_code::SUB_A_D       , ez80_arg::A    , ez80_arg::D    },
	{ez80_op_code::SUB_A_E       , ez80_arg::A    , ez80_arg::E    },
	{ez80_op_code::SUB_A_H       , ez80_arg::A    , ez80_arg::H    },
	{ez80_op_code::SUB_A_L       , ez80_arg::A    , ez80_arg::L    },
	{ez80_op_code::SUB_A_IXH     , ez80_arg::A    , ez80_arg::IXH  },
	{ez80_op_code::SUB_A_IXL     , ez80_arg::A    , ez80_arg::IXL  },
	{ez80_op_code::SUB_A_IYH     , ez80_arg::A    , ez80_arg::IYH  },
	{ez80_op_code::SUB_A_IYL     , ez80_arg::A    , ez80_arg::IYL  },
	{ez80_op_code::SUB_A_PHL     , ez80_arg::A    , ez80_arg::PHL  },
	{ez80_op_code::SUB_A_PIX     , ez80_arg::A    , ez80_arg::PIX  },
	{ez80_op_code::SUB_A_PIY     , ez80_arg::A    , ez80_arg::PIY  },

	{ez80_op_code::SBC_A_N       , ez80_arg::A    , ez80_arg::IMM  },
	{ez80_op_code::SBC_A_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SBC_A_B       , ez80_arg::A    , ez80_arg::B    },
	{ez80_op_code::SBC_A_C       , ez80_arg::A    , ez80_arg::C    },
	{ez80_op_code::SBC_A_D       , ez80_arg::A    , ez80_arg::D    },
	{ez80_op_code::SBC_A_E       , ez80_arg::A    , ez80_arg::E    },
	{ez80_op_code::SBC_A_H       , ez80_arg::A    , ez80_arg::H    },
	{ez80_op_code::SBC_A_L       , ez80_arg::A    , ez80_arg::L    },
	{ez80_op_code::SBC_A_IXH     , ez80_arg::A    , ez80_arg::IXH  },
	{ez80_op_code::SBC_A_IXL     , ez80_arg::A    , ez80_arg::IXL  },
	{ez80_op_code::SBC_A_IYH     , ez80_arg::A    , ez80_arg::IYH  },
	{ez80_op_code::SBC_A_IYL     , ez80_arg::A    , ez80_arg::IYL  },
	{ez80_op_code::SBC_A_PHL     , ez80_arg::A    , ez80_arg::PHL  },
	{ez80_op_code::SBC_A_PIX     , ez80_arg::A    , ez80_arg::PIX  },
	{ez80_op_code::SBC_A_PIY     , ez80_arg::A    , ez80_arg::PIY  },

	{ez80_op_code::CP_A_N        , ez80_arg::A    , ez80_arg::IMM  },
	{ez80_op_code::CP_A_A        , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::CP_A_B        , ez80_arg::A    , ez80_arg::B    },
	{ez80_op_code::CP_A_C        , ez80_arg::A    , ez80_arg::C    },
	{ez80_op_code::CP_A_D        , ez80_arg::A    , ez80_arg::D    },
	{ez80_op_code::CP_A_E        , ez80_arg::A    , ez80_arg::E    },
	{ez80_op_code::CP_A_H        , ez80_arg::A    , ez80_arg::H    },
	{ez80_op_code::CP_A_L        , ez80_arg::A    , ez80_arg::L    },
	{ez80_op_code::CP_A_IXH      , ez80_arg::A    , ez80_arg::IXH  },
	{ez80_op_code::CP_A_IXL      , ez80_arg::A    , ez80_arg::IXL  },
	{ez80_op_code::CP_A_IYH      , ez80_arg::A    , ez80_arg::IYH  },
	{ez80_op_code::CP_A_IYL      , ez80_arg::A    , ez80_arg::IYL  },
	{ez80_op_code::CP_A_PHL      , ez80_arg::A    , ez80_arg::PHL  },
	{ez80_op_code::CP_A_PIX      , ez80_arg::A    , ez80_arg::PIX  },
	{ez80_op_code::CP_A_PIY      , ez80_arg::A    , ez80_arg::PIY  },

	/* Accumulate Logical */

	{ez80_op_code::AND_A_N       , ez80_arg::A    , ez80_arg::IMM  },
	{ez80_op_code::AND_A_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::AND_A_B       , ez80_arg::A    , ez80_arg::B    },
	{ez80_op_code::AND_A_C       , ez80_arg::A    , ez80_arg::C    },
	{ez80_op_code::AND_A_D       , ez80_arg::A    , ez80_arg::D    },
	{ez80_op_code::AND_A_E       , ez80_arg::A    , ez80_arg::E    },
	{ez80_op_code::AND_A_H       , ez80_arg::A    , ez80_arg::H    },
	{ez80_op_code::AND_A_L       , ez80_arg::A    , ez80_arg::L    },
	{ez80_op_code::AND_A_IXH     , ez80_arg::A    , ez80_arg::IXH  },
	{ez80_op_code::AND_A_IXL     , ez80_arg::A    , ez80_arg::IXL  },
	{ez80_op_code::AND_A_IYH     , ez80_arg::A    , ez80_arg::IYH  },
	{ez80_op_code::AND_A_IYL     , ez80_arg::A    , ez80_arg::IYL  },
	{ez80_op_code::AND_A_PHL     , ez80_arg::A    , ez80_arg::PHL  },
	{ez80_op_code::AND_A_PIX     , ez80_arg::A    , ez80_arg::PIX  },
	{ez80_op_code::AND_A_PIY     , ez80_arg::A    , ez80_arg::PIY  },

	{ez80_op_code::OR_A_N        , ez80_arg::A    , ez80_arg::IMM  },
	{ez80_op_code::OR_A_A        , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::OR_A_B        , ez80_arg::A    , ez80_arg::B    },
	{ez80_op_code::OR_A_C        , ez80_arg::A    , ez80_arg::C    },
	{ez80_op_code::OR_A_D        , ez80_arg::A    , ez80_arg::D    },
	{ez80_op_code::OR_A_E        , ez80_arg::A    , ez80_arg::E    },
	{ez80_op_code::OR_A_H        , ez80_arg::A    , ez80_arg::H    },
	{ez80_op_code::OR_A_L        , ez80_arg::A    , ez80_arg::L    },
	{ez80_op_code::OR_A_IXH      , ez80_arg::A    , ez80_arg::IXH  },
	{ez80_op_code::OR_A_IXL      , ez80_arg::A    , ez80_arg::IXL  },
	{ez80_op_code::OR_A_IYH      , ez80_arg::A    , ez80_arg::IYH  },
	{ez80_op_code::OR_A_IYL      , ez80_arg::A    , ez80_arg::IYL  },
	{ez80_op_code::OR_A_PHL      , ez80_arg::A    , ez80_arg::PHL  },
	{ez80_op_code::OR_A_PIX      , ez80_arg::A    , ez80_arg::PIX  },
	{ez80_op_code::OR_A_PIY      , ez80_arg::A    , ez80_arg::PIY  },

	{ez80_op_code::XOR_A_N       , ez80_arg::A    , ez80_arg::IMM  },
	{ez80_op_code::XOR_A_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::XOR_A_B       , ez80_arg::A    , ez80_arg::B    },
	{ez80_op_code::XOR_A_C       , ez80_arg::A    , ez80_arg::C    },
	{ez80_op_code::XOR_A_D       , ez80_arg::A    , ez80_arg::D    },
	{ez80_op_code::XOR_A_E       , ez80_arg::A    , ez80_arg::E    },
	{ez80_op_code::XOR_A_H       , ez80_arg::A    , ez80_arg::H    },
	{ez80_op_code::XOR_A_L       , ez80_arg::A    , ez80_arg::L    },
	{ez80_op_code::XOR_A_IXH     , ez80_arg::A    , ez80_arg::IXH  },
	{ez80_op_code::XOR_A_IXL     , ez80_arg::A    , ez80_arg::IXL  },
	{ez80_op_code::XOR_A_IYH     , ez80_arg::A    , ez80_arg::IYH  },
	{ez80_op_code::XOR_A_IYL     , ez80_arg::A    , ez80_arg::IYL  },
	{ez80_op_code::XOR_A_PHL     , ez80_arg::A    , ez80_arg::PHL  },
	{ez80_op_code::XOR_A_PIX     , ez80_arg::A    , ez80_arg::PIX  },
	{ez80_op_code::XOR_A_PIY     , ez80_arg::A    , ez80_arg::PIY  },

	/* Test A */

	{ez80_op_code::TST_A_N       , ez80_arg::A    , ez80_arg::IMM  },
	{ez80_op_code::TST_A_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::TST_A_B       , ez80_arg::A    , ez80_arg::B    },
	{ez80_op_code::TST_A_C       , ez80_arg::A    , ez80_arg::C    },
	{ez80_op_code::TST_A_D       , ez80_arg::A    , ez80_arg::D    },
	{ez80_op_code::TST_A_E       , ez80_arg::A    , ez80_arg::E    },
	{ez80_op_code::TST_A_H       , ez80_arg::A    , ez80_arg::H    },
	{ez80_op_code::TST_A_L       , ez80_arg::A    , ez80_arg::L    },
	{ez80_op_code::TST_A_PHL     , ez80_arg::A    , ez80_arg::PHL  },

	/* Shift Reg8 */

	{ez80_op_code::RL_A          , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RL_B          , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RL_C          , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RL_D          , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RL_E          , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RL_H          , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RL_L          , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RL_PHL        , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RL_PIX        , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RL_PIY        , ez80_arg::PIY  , ez80_arg::PIY  },

	{ez80_op_code::RLC_A         , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RLC_B         , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RLC_C         , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RLC_D         , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RLC_E         , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RLC_H         , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RLC_L         , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RLC_PHL       , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RLC_PIX       , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RLC_PIY       , ez80_arg::PIY  , ez80_arg::PIY  },

	{ez80_op_code::RR_A          , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RR_B          , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RR_C          , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RR_D          , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RR_E          , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RR_H          , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RR_L          , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RR_PHL        , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RR_PIX        , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RR_PIY        , ez80_arg::PIY  , ez80_arg::PIY  },

	{ez80_op_code::RRC_A         , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RRC_B         , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RRC_C         , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RRC_D         , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RRC_E         , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RRC_H         , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RRC_L         , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RRC_PHL       , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RRC_PIX       , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RRC_PIY       , ez80_arg::PIY  , ez80_arg::PIY  },

	{ez80_op_code::SLA_A         , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SLA_B         , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SLA_C         , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SLA_D         , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SLA_E         , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SLA_H         , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SLA_L         , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SLA_PHL       , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SLA_PIX       , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SLA_PIY       , ez80_arg::PIY  , ez80_arg::PIY  },

	{ez80_op_code::SRA_A         , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SRA_B         , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SRA_C         , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SRA_D         , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SRA_E         , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SRA_H         , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SRA_L         , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SRA_PHL       , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SRA_PIX       , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SRA_PIY       , ez80_arg::PIY  , ez80_arg::PIY  },

	{ez80_op_code::SRL_A         , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SRL_B         , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SRL_C         , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SRL_D         , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SRL_E         , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SRL_H         , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SRL_L         , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SRL_PHL       , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SRL_PIX       , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SRL_PIY       , ez80_arg::PIY  , ez80_arg::PIY  },

	/* load register A */

	{ez80_op_code::LD_A_N        , ez80_arg::A    , ez80_arg::IMM  },
	{ez80_op_code::LD_A_A        , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::LD_A_B        , ez80_arg::A    , ez80_arg::B    },
	{ez80_op_code::LD_A_C        , ez80_arg::A    , ez80_arg::C    },
	{ez80_op_code::LD_A_D        , ez80_arg::A    , ez80_arg::D    },
	{ez80_op_code::LD_A_E        , ez80_arg::A    , ez80_arg::E    },
	{ez80_op_code::LD_A_H        , ez80_arg::A    , ez80_arg::H    },
	{ez80_op_code::LD_A_L        , ez80_arg::A    , ez80_arg::L    },
	{ez80_op_code::LD_A_IXH      , ez80_arg::A    , ez80_arg::IXH  },
	{ez80_op_code::LD_A_IXL      , ez80_arg::A    , ez80_arg::IXL  },
	{ez80_op_code::LD_A_IYH      , ez80_arg::A    , ez80_arg::IYH  },
	{ez80_op_code::LD_A_IYL      , ez80_arg::A    , ez80_arg::IYL  },

	{ez80_op_code::LD_A_ADDR     , ez80_arg::A    , ez80_arg::ADDR },
	{ez80_op_code::LD_A_PBC      , ez80_arg::A    , ez80_arg::PBC  },
	{ez80_op_code::LD_A_PDE      , ez80_arg::A    , ez80_arg::PDE  },
	{ez80_op_code::LD_A_PHL      , ez80_arg::A    , ez80_arg::PHL  },
	{ez80_op_code::LD_A_PIX      , ez80_arg::A    , ez80_arg::PIX  },
	{ez80_op_code::LD_A_PIY      , ez80_arg::A    , ez80_arg::PIY  },

	/* load B C D E */

	{ez80_op_code::LD_B_N        , ez80_arg::B    , ez80_arg::IMM  },
	{ez80_op_code::LD_B_A        , ez80_arg::B    , ez80_arg::A    },
	{ez80_op_code::LD_B_C        , ez80_arg::B    , ez80_arg::C    },
	{ez80_op_code::LD_B_D        , ez80_arg::B    , ez80_arg::D    },
	{ez80_op_code::LD_B_E        , ez80_arg::B    , ez80_arg::E    },
	{ez80_op_code::LD_B_H        , ez80_arg::B    , ez80_arg::H    },
	{ez80_op_code::LD_B_L        , ez80_arg::B    , ez80_arg::L    },
	{ez80_op_code::LD_B_IXH      , ez80_arg::B    , ez80_arg::IXH  },
	{ez80_op_code::LD_B_IXL      , ez80_arg::B    , ez80_arg::IXL  },
	{ez80_op_code::LD_B_IYH      , ez80_arg::B    , ez80_arg::IYH  },
	{ez80_op_code::LD_B_IYL      , ez80_arg::B    , ez80_arg::IYL  },
	{ez80_op_code::LD_B_PHL      , ez80_arg::B    , ez80_arg::PHL  },
	{ez80_op_code::LD_B_PIX      , ez80_arg::B    , ez80_arg::PIX  },
	{ez80_op_code::LD_B_PIY      , ez80_arg::B    , ez80_arg::PIY  },

	{ez80_op_code::LD_C_N        , ez80_arg::C    , ez80_arg::IMM  },
	{ez80_op_code::LD_C_A        , ez80_arg::C    , ez80_arg::A    },
	{ez80_op_code::LD_C_B        , ez80_arg::C    , ez80_arg::B    },
	{ez80_op_code::LD_C_D        , ez80_arg::C    , ez80_arg::D    },
	{ez80_op_code::LD_C_E        , ez80_arg::C    , ez80_arg::E    },
	{ez80_op_code::LD_C_H        , ez80_arg::C    , ez80_arg::H    },
	{ez80_op_code::LD_C_L        , ez80_arg::C    , ez80_arg::L    },
	{ez80_op_code::LD_C_IXH      , ez80_arg::C    , ez80_arg::IXH  },
	{ez80_op_code::LD_C_IXL      , ez80_arg::C    , ez80_arg::IXL  },
	{ez80_op_code::LD_C_IYH      , ez80_arg::C    , ez80_arg::IYH  },
	{ez80_op_code::LD_C_IYL      , ez80_arg::C    , ez80_arg::IYL  },
	{ez80_op_code::LD_C_PHL      , ez80_arg::C    , ez80_arg::PHL  },
	{ez80_op_code::LD_C_PIX      , ez80_arg::C    , ez80_arg::PIX  },
	{ez80_op_code::LD_C_PIY      , ez80_arg::C    , ez80_arg::PIY  },

	{ez80_op_code::LD_D_N        , ez80_arg::D    , ez80_arg::IMM  },
	{ez80_op_code::LD_D_A        , ez80_arg::D    , ez80_arg::A    },
	{ez80_op_code::LD_D_B        , ez80_arg::D    , ez80_arg::B    },
	{ez80_op_code::LD_D_C        , ez80_arg::D    , ez80_arg::C    },
	{ez80_op_code::LD_D_E        , ez80_arg::D    , ez80_arg::E    },
	{ez80_op_code::LD_D_H        , ez80_arg::D    , ez80_arg::H    },
	{ez80_op_code::LD_D_L        , ez80_arg::D    , ez80_arg::L    },
	{ez80_op_code::LD_D_IXH      , ez80_arg::D    , ez80_arg::IXH  },
	{ez80_op_code::LD_D_IXL      , ez80_arg::D    , ez80_arg::IXL  },
	{ez80_op_code::LD_D_IYH      , ez80_arg::D    , ez80_arg::IYH  },
	{ez80_op_code::LD_D_IYL      , ez80_arg::D    , ez80_arg::IYL  },
	{ez80_op_code::LD_D_PHL      , ez80_arg::D    , ez80_arg::PHL  },
	{ez80_op_code::LD_D_PIX      , ez80_arg::D    , ez80_arg::PIX  },
	{ez80_op_code::LD_D_PIY      , ez80_arg::D    , ez80_arg::PIY  },

	{ez80_op_code::LD_E_N        , ez80_arg::E    , ez80_arg::IMM  },
	{ez80_op_code::LD_E_A        , ez80_arg::E    , ez80_arg::A    },
	{ez80_op_code::LD_E_B        , ez80_arg::E    , ez80_arg::B    },
	{ez80_op_code::LD_E_C        , ez80_arg::E    , ez80_arg::C    },
	{ez80_op_code::LD_E_D        , ez80_arg::E    , ez80_arg::D    },
	{ez80_op_code::LD_E_H        , ez80_arg::E    , ez80_arg::H    },
	{ez80_op_code::LD_E_L        , ez80_arg::E    , ez80_arg::L    },
	{ez80_op_code::LD_E_IXH      , ez80_arg::E    , ez80_arg::IXH  },
	{ez80_op_code::LD_E_IXL      , ez80_arg::E    , ez80_arg::IXL  },
	{ez80_op_code::LD_E_IYH      , ez80_arg::E    , ez80_arg::IYH  },
	{ez80_op_code::LD_E_IYL      , ez80_arg::E    , ez80_arg::IYL  },
	{ez80_op_code::LD_E_PHL      , ez80_arg::E    , ez80_arg::PHL  },
	{ez80_op_code::LD_E_PIX      , ez80_arg::E    , ez80_arg::PIX  },
	{ez80_op_code::LD_E_PIY      , ez80_arg::E    , ez80_arg::PIY  },

	/* load H L */

	{ez80_op_code::LD_H_N        , ez80_arg::H    , ez80_arg::IMM  },
	{ez80_op_code::LD_H_A        , ez80_arg::H    , ez80_arg::A    },
	{ez80_op_code::LD_H_B        , ez80_arg::H    , ez80_arg::B    },
	{ez80_op_code::LD_H_C        , ez80_arg::H    , ez80_arg::C    },
	{ez80_op_code::LD_H_D        , ez80_arg::H    , ez80_arg::D    },
	{ez80_op_code::LD_H_E        , ez80_arg::H    , ez80_arg::E    },
	{ez80_op_code::LD_H_H        , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::LD_H_L        , ez80_arg::H    , ez80_arg::L    },
	{ez80_op_code::LD_H_PHL      , ez80_arg::H    , ez80_arg::PHL  },
	{ez80_op_code::LD_H_PIX      , ez80_arg::H    , ez80_arg::PIX  },
	{ez80_op_code::LD_H_PIY      , ez80_arg::H    , ez80_arg::PIY  },

	{ez80_op_code::LD_L_N        , ez80_arg::L    , ez80_arg::IMM  },
	{ez80_op_code::LD_L_A        , ez80_arg::L    , ez80_arg::A    },
	{ez80_op_code::LD_L_B        , ez80_arg::L    , ez80_arg::B    },
	{ez80_op_code::LD_L_C        , ez80_arg::L    , ez80_arg::C    },
	{ez80_op_code::LD_L_D        , ez80_arg::L    , ez80_arg::D    },
	{ez80_op_code::LD_L_E        , ez80_arg::L    , ez80_arg::E    },
	{ez80_op_code::LD_L_H        , ez80_arg::L    , ez80_arg::H    },
	{ez80_op_code::LD_L_L        , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::LD_L_PHL      , ez80_arg::L    , ez80_arg::PHL  },
	{ez80_op_code::LD_L_PIX      , ez80_arg::L    , ez80_arg::PIX  },
	{ez80_op_code::LD_L_PIY      , ez80_arg::L    , ez80_arg::PIY  },

	/* load IXL IXH IYL IYH */

	{ez80_op_code::LD_IXH_N      , ez80_arg::IXH  , ez80_arg::IMM  },
	{ez80_op_code::LD_IXH_A      , ez80_arg::IXH  , ez80_arg::A    },
	{ez80_op_code::LD_IXH_B      , ez80_arg::IXH  , ez80_arg::B    },
	{ez80_op_code::LD_IXH_C      , ez80_arg::IXH  , ez80_arg::C    },
	{ez80_op_code::LD_IXH_D      , ez80_arg::IXH  , ez80_arg::D    },
	{ez80_op_code::LD_IXH_E      , ez80_arg::IXH  , ez80_arg::E    },
	{ez80_op_code::LD_IXH_IXH    , ez80_arg::IXH  , ez80_arg::IXH  },
	{ez80_op_code::LD_IXH_IXL    , ez80_arg::IXH  , ez80_arg::IXL  },

	{ez80_op_code::LD_IXL_N      , ez80_arg::IXL  , ez80_arg::IMM  },
	{ez80_op_code::LD_IXL_A      , ez80_arg::IXL  , ez80_arg::A    },
	{ez80_op_code::LD_IXL_B      , ez80_arg::IXL  , ez80_arg::B    },
	{ez80_op_code::LD_IXL_C      , ez80_arg::IXL  , ez80_arg::C    },
	{ez80_op_code::LD_IXL_D      , ez80_arg::IXL  , ez80_arg::D    },
	{ez80_op_code::LD_IXL_E      , ez80_arg::IXL  , ez80_arg::E    },
	{ez80_op_code::LD_IXL_IXH    , ez80_arg::IXL  , ez80_arg::IXH  },
	{ez80_op_code::LD_IXL_IXL    , ez80_arg::IXL  , ez80_arg::IXL  },

	{ez80_op_code::LD_IYH_N      , ez80_arg::IYH  , ez80_arg::IMM  },
	{ez80_op_code::LD_IYH_A      , ez80_arg::IYH  , ez80_arg::A    },
	{ez80_op_code::LD_IYH_B      , ez80_arg::IYH  , ez80_arg::B    },
	{ez80_op_code::LD_IYH_C      , ez80_arg::IYH  , ez80_arg::C    },
	{ez80_op_code::LD_IYH_D      , ez80_arg::IYH  , ez80_arg::D    },
	{ez80_op_code::LD_IYH_E      , ez80_arg::IYH  , ez80_arg::E    },
	{ez80_op_code::LD_IYH_IYH    , ez80_arg::IYH  , ez80_arg::IYH  },
	{ez80_op_code::LD_IYH_IYL    , ez80_arg::IYH  , ez80_arg::IYL  },

	{ez80_op_code::LD_IYL_N      , ez80_arg::IYL  , ez80_arg::IMM  },
	{ez80_op_code::LD_IYL_A      , ez80_arg::IYL  , ez80_arg::A    },
	{ez80_op_code::LD_IYL_B      , ez80_arg::IYL  , ez80_arg::B    },
	{ez80_op_code::LD_IYL_C      , ez80_arg::IYL  , ez80_arg::C    },
	{ez80_op_code::LD_IYL_D      , ez80_arg::IYL  , ez80_arg::D    },
	{ez80_op_code::LD_IYL_E      , ez80_arg::IYL  , ez80_arg::E    },
	{ez80_op_code::LD_IYL_IYH    , ez80_arg::IYL  , ez80_arg::IYH  },
	{ez80_op_code::LD_IYL_IYL    , ez80_arg::IYL  , ez80_arg::IYL  },

	/* load HL */

	{ez80_op_code::LD_HL_N       , ez80_arg::HL   , ez80_arg::IMM   },
	{ez80_op_code::LD_HL_N_SIS   , ez80_arg::HL   , ez80_arg::IMM   },
	{ez80_op_code::LD_HL_ADDR    , ez80_arg::HL   , ez80_arg::ADDR  },
	{ez80_op_code::LD_HL_PHL     , ez80_arg::HL   , ez80_arg::PHL   },
	{ez80_op_code::LD_HL_PIX     , ez80_arg::HL   , ez80_arg::PIX   },
	{ez80_op_code::LD_HL_PIY     , ez80_arg::HL   , ez80_arg::PIY   },

	/* load reg24 */

	{ez80_op_code::LD_BC_N       , ez80_arg::BC   , ez80_arg::IMM   },
	{ez80_op_code::LD_BC_N_SIS   , ez80_arg::BC   , ez80_arg::IMM   },
	{ez80_op_code::LD_BC_ADDR    , ez80_arg::BC   , ez80_arg::ADDR  },
	{ez80_op_code::LD_BC_PHL     , ez80_arg::BC   , ez80_arg::PHL   },
	{ez80_op_code::LD_BC_PIX     , ez80_arg::BC   , ez80_arg::PIX   },
	{ez80_op_code::LD_BC_PIY     , ez80_arg::BC   , ez80_arg::PIY   },

	{ez80_op_code::LD_DE_N       , ez80_arg::DE   , ez80_arg::IMM   },
	{ez80_op_code::LD_DE_N_SIS   , ez80_arg::DE   , ez80_arg::IMM   },
	{ez80_op_code::LD_DE_ADDR    , ez80_arg::DE   , ez80_arg::ADDR  },
	{ez80_op_code::LD_DE_PHL     , ez80_arg::DE   , ez80_arg::PHL   },
	{ez80_op_code::LD_DE_PIX     , ez80_arg::DE   , ez80_arg::PIX   },
	{ez80_op_code::LD_DE_PIY     , ez80_arg::DE   , ez80_arg::PIY   },

	/* load SP */

	{ez80_op_code::LD_SP_N       , ez80_arg::SP   , ez80_arg::IMM   },
	{ez80_op_code::LD_SP_N_SIS   , ez80_arg::SP   , ez80_arg::IMM   },
	{ez80_op_code::LD_SP_HL      , ez80_arg::SP   , ez80_arg::HL    },
	{ez80_op_code::LD_SP_IX      , ez80_arg::SP   , ez80_arg::IX    },
	{ez80_op_code::LD_SP_IY      , ez80_arg::SP   , ez80_arg::IY    },
	{ez80_op_code::LD_SP_ADDR    , ez80_arg::SP   , ez80_arg::ADDR  },

	/* load IX IY */

	{ez80_op_code::LD_IX_N       , ez80_arg::IX   , ez80_arg::IMM   },
	{ez80_op_code::LD_IX_N_SIS   , ez80_arg::IX   , ez80_arg::IMM   },
	{ez80_op_code::LD_IX_ADDR    , ez80_arg::IX   , ez80_arg::ADDR  },
	{ez80_op_code::LD_IX_PHL     , ez80_arg::IX   , ez80_arg::PHL   },
	{ez80_op_code::LD_IX_PIX     , ez80_arg::IX   , ez80_arg::PIX   },
	{ez80_op_code::LD_IX_PIY     , ez80_arg::IX   , ez80_arg::PIY   },

	{ez80_op_code::LD_IY_N       , ez80_arg::IY   , ez80_arg::IMM   },
	{ez80_op_code::LD_IY_N_SIS   , ez80_arg::IY   , ez80_arg::IMM   },
	{ez80_op_code::LD_IY_ADDR    , ez80_arg::IY   , ez80_arg::ADDR  },
	{ez80_op_code::LD_IY_PHL     , ez80_arg::IY   , ez80_arg::PHL   },
	{ez80_op_code::LD_IY_PIX     , ez80_arg::IY   , ez80_arg::PIX   },
	{ez80_op_code::LD_IY_PIY     , ez80_arg::IY   , ez80_arg::PIY   },

	/* store register A */

	{ez80_op_code::LD_ADDR_A     , ez80_arg::ADDR , ez80_arg::A    },

	{ez80_op_code::LD_PBC_A      , ez80_arg::PBC  , ez80_arg::A    },
	{ez80_op_code::LD_PDE_A      , ez80_arg::PDE  , ez80_arg::A    },
	{ez80_op_code::LD_PHL_A      , ez80_arg::PHL  , ez80_arg::A    },

	/* store reg8 */

	{ez80_op_code::LD_PHL_N      , ez80_arg::PHL  , ez80_arg::IMM  },
	{ez80_op_code::LD_PHL_B      , ez80_arg::PHL  , ez80_arg::B    },
	{ez80_op_code::LD_PHL_C      , ez80_arg::PHL  , ez80_arg::C    },
	{ez80_op_code::LD_PHL_D      , ez80_arg::PHL  , ez80_arg::D    },
	{ez80_op_code::LD_PHL_E      , ez80_arg::PHL  , ez80_arg::E    },
	{ez80_op_code::LD_PHL_H      , ez80_arg::PHL  , ez80_arg::H    },
	{ez80_op_code::LD_PHL_L      , ez80_arg::PHL  , ez80_arg::L    },

	{ez80_op_code::LD_PIX_N      , ez80_arg::PIX  , ez80_arg::IMM  },
	{ez80_op_code::LD_PIX_A      , ez80_arg::PIX  , ez80_arg::A    },
	{ez80_op_code::LD_PIX_B      , ez80_arg::PIX  , ez80_arg::B    },
	{ez80_op_code::LD_PIX_C      , ez80_arg::PIX  , ez80_arg::C    },
	{ez80_op_code::LD_PIX_D      , ez80_arg::PIX  , ez80_arg::D    },
	{ez80_op_code::LD_PIX_E      , ez80_arg::PIX  , ez80_arg::E    },
	{ez80_op_code::LD_PIX_H      , ez80_arg::PIX  , ez80_arg::H    },
	{ez80_op_code::LD_PIX_L      , ez80_arg::PIX  , ez80_arg::L    },

	{ez80_op_code::LD_PIY_N      , ez80_arg::PIY  , ez80_arg::IMM  },
	{ez80_op_code::LD_PIY_A      , ez80_arg::PIY  , ez80_arg::A    },
	{ez80_op_code::LD_PIY_B      , ez80_arg::PIY  , ez80_arg::B    },
	{ez80_op_code::LD_PIY_C      , ez80_arg::PIY  , ez80_arg::C    },
	{ez80_op_code::LD_PIY_D      , ez80_arg::PIY  , ez80_arg::D    },
	{ez80_op_code::LD_PIY_E      , ez80_arg::PIY  , ez80_arg::E    },
	{ez80_op_code::LD_PIY_H      , ez80_arg::PIY  , ez80_arg::H    },
	{ez80_op_code::LD_PIY_L      , ez80_arg::PIY  , ez80_arg::L    },

	/* write reg24 to address */

	{ez80_op_code::LD_ADDR_HL    , ez80_arg::ADDR , ez80_arg::HL   },

	{ez80_op_code::LD_ADDR_BC    , ez80_arg::ADDR , ez80_arg::BC   },
	{ez80_op_code::LD_ADDR_DE    , ez80_arg::ADDR , ez80_arg::DE   },
	{ez80_op_code::LD_ADDR_IX    , ez80_arg::ADDR , ez80_arg::IX   },
	{ez80_op_code::LD_ADDR_IY    , ez80_arg::ADDR , ez80_arg::IY   },
	{ez80_op_code::LD_ADDR_SP    , ez80_arg::ADDR , ez80_arg::SP   },

	/* store reg24 */

	{ez80_op_code::LD_PHL_BC     , ez80_arg::PHL  , ez80_arg::BC   },
	{ez80_op_code::LD_PHL_DE     , ez80_arg::PHL  , ez80_arg::DE   },
	{ez80_op_code::LD_PHL_HL     , ez80_arg::PHL  , ez80_arg::HL   },
	{ez80_op_code::LD_PHL_IX     , ez80_arg::PHL  , ez80_arg::IX   },
	{ez80_op_code::LD_PHL_IY     , ez80_arg::PHL  , ez80_arg::IY   },

	{ez80_op_code::LD_PIX_BC     , ez80_arg::PIX  , ez80_arg::BC   },
	{ez80_op_code::LD_PIX_HL     , ez80_arg::PIX  , ez80_arg::HL   },
	{ez80_op_code::LD_PIX_DE     , ez80_arg::PIX  , ez80_arg::DE   },
	{ez80_op_code::LD_PIX_IX     , ez80_arg::PIX  , ez80_arg::IX   },
	{ez80_op_code::LD_PIX_IY     , ez80_arg::PIX  , ez80_arg::IY   },

	{ez80_op_code::LD_PIY_BC     , ez80_arg::PIY  , ez80_arg::BC   },
	{ez80_op_code::LD_PIY_HL     , ez80_arg::PIY  , ez80_arg::HL   },
	{ez80_op_code::LD_PIY_DE     , ez80_arg::PIY  , ez80_arg::DE   },
	{ez80_op_code::LD_PIY_IX     , ez80_arg::PIY  , ez80_arg::IX   },
	{ez80_op_code::LD_PIY_IY     , ez80_arg::PIY  , ez80_arg::IY   },

	/* load effective address */

	{ez80_op_code::LEA_BC_IX     , ez80_arg::BC   , ez80_arg::IX   },
	{ez80_op_code::LEA_BC_IY     , ez80_arg::BC   , ez80_arg::IY   },
	{ez80_op_code::LEA_DE_IX     , ez80_arg::DE   , ez80_arg::IX   },
	{ez80_op_code::LEA_DE_IY     , ez80_arg::DE   , ez80_arg::IY   },
	{ez80_op_code::LEA_HL_IX     , ez80_arg::HL   , ez80_arg::IX   },
	{ez80_op_code::LEA_HL_IY     , ez80_arg::HL   , ez80_arg::IY   },
	{ez80_op_code::LEA_IX_IX     , ez80_arg::IX   , ez80_arg::IX   },
	{ez80_op_code::LEA_IX_IY     , ez80_arg::IX   , ez80_arg::IY   },
	{ez80_op_code::LEA_IY_IX     , ez80_arg::IY   , ez80_arg::IX   },
	{ez80_op_code::LEA_IY_IY     , ez80_arg::IY   , ez80_arg::IY   },

	{ez80_op_code::LEA_BC_IX_SIS , ez80_arg::BC   , ez80_arg::IX   },
	{ez80_op_code::LEA_BC_IY_SIS , ez80_arg::BC   , ez80_arg::IY   },
	{ez80_op_code::LEA_DE_IX_SIS , ez80_arg::DE   , ez80_arg::IX   },
	{ez80_op_code::LEA_DE_IY_SIS , ez80_arg::DE   , ez80_arg::IY   },
	{ez80_op_code::LEA_HL_IX_SIS , ez80_arg::HL   , ez80_arg::IX   },
	{ez80_op_code::LEA_HL_IY_SIS , ez80_arg::HL   , ez80_arg::IY   },
	{ez80_op_code::LEA_IX_IX_SIS , ez80_arg::IX   , ez80_arg::IX   },
	{ez80_op_code::LEA_IX_IY_SIS , ez80_arg::IX   , ez80_arg::IY   },
	{ez80_op_code::LEA_IY_IX_SIS , ez80_arg::IY   , ez80_arg::IX   },
	{ez80_op_code::LEA_IY_IY_SIS , ez80_arg::IY   , ez80_arg::IY   },

	/* Test bits */

	{ez80_op_code::BIT_0_A       , ez80_arg::NONE , ez80_arg::A    },
	{ez80_op_code::BIT_0_B       , ez80_arg::NONE , ez80_arg::B    },
	{ez80_op_code::BIT_0_C       , ez80_arg::NONE , ez80_arg::C    },
	{ez80_op_code::BIT_0_D       , ez80_arg::NONE , ez80_arg::D    },
	{ez80_op_code::BIT_0_E       , ez80_arg::NONE , ez80_arg::E    },
	{ez80_op_code::BIT_0_H       , ez80_arg::NONE , ez80_arg::H    },
	{ez80_op_code::BIT_0_L       , ez80_arg::NONE , ez80_arg::L    },
	{ez80_op_code::BIT_0_PHL     , ez80_arg::NONE , ez80_arg::PHL  },
	{ez80_op_code::BIT_0_PIX     , ez80_arg::NONE , ez80_arg::PIX  },
	{ez80_op_code::BIT_0_PIY     , ez80_arg::NONE , ez80_arg::PIY  },
	{ez80_op_code::BIT_1_A       , ez80_arg::NONE , ez80_arg::A    },
	{ez80_op_code::BIT_1_B       , ez80_arg::NONE , ez80_arg::B    },
	{ez80_op_code::BIT_1_C       , ez80_arg::NONE , ez80_arg::C    },
	{ez80_op_code::BIT_1_D       , ez80_arg::NONE , ez80_arg::D    },
	{ez80_op_code::BIT_1_E       , ez80_arg::NONE , ez80_arg::E    },
	{ez80_op_code::BIT_1_H       , ez80_arg::NONE , ez80_arg::H    },
	{ez80_op_code::BIT_1_L       , ez80_arg::NONE , ez80_arg::L    },
	{ez80_op_code::BIT_1_PHL     , ez80_arg::NONE , ez80_arg::PHL  },
	{ez80_op_code::BIT_1_PIX     , ez80_arg::NONE , ez80_arg::PIX  },
	{ez80_op_code::BIT_1_PIY     , ez80_arg::NONE , ez80_arg::PIY  },
	{ez80_op_code::BIT_2_A       , ez80_arg::NONE , ez80_arg::A    },
	{ez80_op_code::BIT_2_B       , ez80_arg::NONE , ez80_arg::B    },
	{ez80_op_code::BIT_2_C       , ez80_arg::NONE , ez80_arg::C    },
	{ez80_op_code::BIT_2_D       , ez80_arg::NONE , ez80_arg::D    },
	{ez80_op_code::BIT_2_E       , ez80_arg::NONE , ez80_arg::E    },
	{ez80_op_code::BIT_2_H       , ez80_arg::NONE , ez80_arg::H    },
	{ez80_op_code::BIT_2_L       , ez80_arg::NONE , ez80_arg::L    },
	{ez80_op_code::BIT_2_PHL     , ez80_arg::NONE , ez80_arg::PHL  },
	{ez80_op_code::BIT_2_PIX     , ez80_arg::NONE , ez80_arg::PIX  },
	{ez80_op_code::BIT_2_PIY     , ez80_arg::NONE , ez80_arg::PIY  },
	{ez80_op_code::BIT_3_A       , ez80_arg::NONE , ez80_arg::A    },
	{ez80_op_code::BIT_3_B       , ez80_arg::NONE , ez80_arg::B    },
	{ez80_op_code::BIT_3_C       , ez80_arg::NONE , ez80_arg::C    },
	{ez80_op_code::BIT_3_D       , ez80_arg::NONE , ez80_arg::D    },
	{ez80_op_code::BIT_3_E       , ez80_arg::NONE , ez80_arg::E    },
	{ez80_op_code::BIT_3_H       , ez80_arg::NONE , ez80_arg::H    },
	{ez80_op_code::BIT_3_L       , ez80_arg::NONE , ez80_arg::L    },
	{ez80_op_code::BIT_3_PHL     , ez80_arg::NONE , ez80_arg::PHL  },
	{ez80_op_code::BIT_3_PIX     , ez80_arg::NONE , ez80_arg::PIX  },
	{ez80_op_code::BIT_3_PIY     , ez80_arg::NONE , ez80_arg::PIY  },
	{ez80_op_code::BIT_4_A       , ez80_arg::NONE , ez80_arg::A    },
	{ez80_op_code::BIT_4_B       , ez80_arg::NONE , ez80_arg::B    },
	{ez80_op_code::BIT_4_C       , ez80_arg::NONE , ez80_arg::C    },
	{ez80_op_code::BIT_4_D       , ez80_arg::NONE , ez80_arg::D    },
	{ez80_op_code::BIT_4_E       , ez80_arg::NONE , ez80_arg::E    },
	{ez80_op_code::BIT_4_H       , ez80_arg::NONE , ez80_arg::H    },
	{ez80_op_code::BIT_4_L       , ez80_arg::NONE , ez80_arg::L    },
	{ez80_op_code::BIT_4_PHL     , ez80_arg::NONE , ez80_arg::PHL  },
	{ez80_op_code::BIT_4_PIX     , ez80_arg::NONE , ez80_arg::PIX  },
	{ez80_op_code::BIT_4_PIY     , ez80_arg::NONE , ez80_arg::PIY  },
	{ez80_op_code::BIT_5_A       , ez80_arg::NONE , ez80_arg::A    },
	{ez80_op_code::BIT_5_B       , ez80_arg::NONE , ez80_arg::B    },
	{ez80_op_code::BIT_5_C       , ez80_arg::NONE , ez80_arg::C    },
	{ez80_op_code::BIT_5_D       , ez80_arg::NONE , ez80_arg::D    },
	{ez80_op_code::BIT_5_E       , ez80_arg::NONE , ez80_arg::E    },
	{ez80_op_code::BIT_5_H       , ez80_arg::NONE , ez80_arg::H    },
	{ez80_op_code::BIT_5_L       , ez80_arg::NONE , ez80_arg::L    },
	{ez80_op_code::BIT_5_PHL     , ez80_arg::NONE , ez80_arg::PHL  },
	{ez80_op_code::BIT_5_PIX     , ez80_arg::NONE , ez80_arg::PIX  },
	{ez80_op_code::BIT_5_PIY     , ez80_arg::NONE , ez80_arg::PIY  },
	{ez80_op_code::BIT_6_A       , ez80_arg::NONE , ez80_arg::A    },
	{ez80_op_code::BIT_6_B       , ez80_arg::NONE , ez80_arg::B    },
	{ez80_op_code::BIT_6_C       , ez80_arg::NONE , ez80_arg::C    },
	{ez80_op_code::BIT_6_D       , ez80_arg::NONE , ez80_arg::D    },
	{ez80_op_code::BIT_6_E       , ez80_arg::NONE , ez80_arg::E    },
	{ez80_op_code::BIT_6_H       , ez80_arg::NONE , ez80_arg::H    },
	{ez80_op_code::BIT_6_L       , ez80_arg::NONE , ez80_arg::L    },
	{ez80_op_code::BIT_6_PHL     , ez80_arg::NONE , ez80_arg::PHL  },
	{ez80_op_code::BIT_6_PIX     , ez80_arg::NONE , ez80_arg::PIX  },
	{ez80_op_code::BIT_6_PIY     , ez80_arg::NONE , ez80_arg::PIY  },
	{ez80_op_code::BIT_7_A       , ez80_arg::NONE , ez80_arg::A    },
	{ez80_op_code::BIT_7_B       , ez80_arg::NONE , ez80_arg::B    },
	{ez80_op_code::BIT_7_C       , ez80_arg::NONE , ez80_arg::C    },
	{ez80_op_code::BIT_7_D       , ez80_arg::NONE , ez80_arg::D    },
	{ez80_op_code::BIT_7_E       , ez80_arg::NONE , ez80_arg::E    },
	{ez80_op_code::BIT_7_H       , ez80_arg::NONE , ez80_arg::H    },
	{ez80_op_code::BIT_7_L       , ez80_arg::NONE , ez80_arg::L    },
	{ez80_op_code::BIT_7_PHL     , ez80_arg::NONE , ez80_arg::PHL  },
	{ez80_op_code::BIT_7_PIX     , ez80_arg::NONE , ez80_arg::PIX  },
	{ez80_op_code::BIT_7_PIY     , ez80_arg::NONE , ez80_arg::PIY  },

	/* Set bits */

	{ez80_op_code::SET_0_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SET_0_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SET_0_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SET_0_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SET_0_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SET_0_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SET_0_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SET_0_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SET_0_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SET_0_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::SET_1_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SET_1_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SET_1_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SET_1_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SET_1_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SET_1_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SET_1_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SET_1_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SET_1_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SET_1_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::SET_2_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SET_2_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SET_2_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SET_2_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SET_2_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SET_2_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SET_2_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SET_2_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SET_2_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SET_2_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::SET_3_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SET_3_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SET_3_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SET_3_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SET_3_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SET_3_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SET_3_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SET_3_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SET_3_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SET_3_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::SET_4_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SET_4_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SET_4_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SET_4_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SET_4_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SET_4_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SET_4_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SET_4_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SET_4_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SET_4_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::SET_5_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SET_5_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SET_5_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SET_5_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SET_5_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SET_5_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SET_5_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SET_5_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SET_5_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SET_5_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::SET_6_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SET_6_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SET_6_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SET_6_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SET_6_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SET_6_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SET_6_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SET_6_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SET_6_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SET_6_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::SET_7_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::SET_7_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::SET_7_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::SET_7_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::SET_7_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::SET_7_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::SET_7_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::SET_7_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::SET_7_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::SET_7_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },

	/* Reset bits */

	{ez80_op_code::RES_0_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RES_0_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RES_0_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RES_0_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RES_0_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RES_0_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RES_0_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RES_0_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RES_0_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RES_0_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::RES_1_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RES_1_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RES_1_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RES_1_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RES_1_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RES_1_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RES_1_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RES_1_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RES_1_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RES_1_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::RES_2_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RES_2_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RES_2_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RES_2_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RES_2_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RES_2_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RES_2_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RES_2_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RES_2_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RES_2_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::RES_3_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RES_3_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RES_3_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RES_3_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RES_3_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RES_3_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RES_3_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RES_3_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RES_3_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RES_3_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::RES_4_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RES_4_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RES_4_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RES_4_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RES_4_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RES_4_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RES_4_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RES_4_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RES_4_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RES_4_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::RES_5_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RES_5_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RES_5_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RES_5_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RES_5_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RES_5_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RES_5_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RES_5_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RES_5_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RES_5_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::RES_6_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RES_6_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RES_6_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RES_6_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RES_6_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RES_6_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RES_6_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RES_6_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RES_6_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RES_6_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },
	{ez80_op_code::RES_7_A       , ez80_arg::A    , ez80_arg::A    },
	{ez80_op_code::RES_7_B       , ez80_arg::B    , ez80_arg::B    },
	{ez80_op_code::RES_7_C       , ez80_arg::C    , ez80_arg::C    },
	{ez80_op_code::RES_7_D       , ez80_arg::D    , ez80_arg::D    },
	{ez80_op_code::RES_7_E       , ez80_arg::E    , ez80_arg::E    },
	{ez80_op_code::RES_7_H       , ez80_arg::H    , ez80_arg::H    },
	{ez80_op_code::RES_7_L       , ez80_arg::L    , ez80_arg::L    },
	{ez80_op_code::RES_7_PHL     , ez80_arg::PHL  , ez80_arg::PHL  },
	{ez80_op_code::RES_7_PIX     , ez80_arg::PIX  , ez80_arg::PIX  },
	{ez80_op_code::RES_7_PIY     , ez80_arg::PIY  , ez80_arg::PIY  },

	/* IO instructions */

	{ez80_op_code::IN_A_PBC      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN_A_PN       , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN_B_PBC      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN_C_PBC      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN_D_PBC      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN_E_PBC      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN_H_PBC      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN_L_PBC      , ez80_arg::NONE , ez80_arg::NONE },

	{ez80_op_code::IN0_A_PN      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN0_B_PN      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN0_C_PN      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN0_D_PN      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN0_E_PN      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN0_H_PN      , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IN0_L_PN      , ez80_arg::NONE , ez80_arg::NONE },

	{ez80_op_code::IND           , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IND2          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::IND2R         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::INDM          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::INDMR         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::INDR          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::INDRX         , ez80_arg::NONE , ez80_arg::NONE },

	{ez80_op_code::INI           , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::INI2          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::INI2R         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::INIM          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::INIMR         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::INIR          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::INIRX         , ez80_arg::NONE , ez80_arg::NONE },

	{ez80_op_code::OTD2R         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OTDM          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OTDMR         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OTDR          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OTDRX         , ez80_arg::NONE , ez80_arg::NONE },

	{ez80_op_code::OTI2R         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OTIM          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OTIMR         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OTIR          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OTIRX         , ez80_arg::NONE , ez80_arg::NONE },

	{ez80_op_code::OUT_PBC_A     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT_PBC_B     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT_PBC_C     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT_PBC_D     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT_PBC_E     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT_PBC_H     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT_PBC_L     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT_PN_A      , ez80_arg::NONE , ez80_arg::NONE },

	{ez80_op_code::OUT0_PN_A     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT0_PN_B     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT0_PN_C     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT0_PN_D     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT0_PN_E     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT0_PN_H     , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUT0_PN_L     , ez80_arg::NONE , ez80_arg::NONE },

	{ez80_op_code::OUTD          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUTD2         , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUTI          , ez80_arg::NONE , ez80_arg::NONE },
	{ez80_op_code::OUTI2         , ez80_arg::NONE , ez80_arg::NONE },

	{ez80_op_code::TSTIO         , ez80_arg::NONE , ez80_arg::NONE },

};


#endif /* EZ80_DST_SRC_H */
